version: '3'
services:
  integraservicios-gw:
    container_name: integraservicios-gw
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - is_net
    volumes:
      - ./src:/integraservicios-gw/src

networks:
  is_net:
    name: is_net
